const API=`${window.location.origin}/api/chat`;
const token=localStorage.getItem('token');
if(!token) location.href='login.html';
const bookingId=new URLSearchParams(location.search).get('booking');
const user=(()=>{try{return JSON.parse(localStorage.getItem('user')||'{}')}catch{return {}}})();
const list=document.getElementById('messageList'), form=document.getElementById('chatForm'), input=document.getElementById('messageInput'), errorBox=document.getElementById('chatError');
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function showError(msg){errorBox.hidden=!msg;errorBox.textContent=msg||'';}
function renderMessage(m){const mine=String(m.sender?._id||m.sender)===String(user.id||user._id);const el=document.createElement('article');el.className=`chat-message${mine?' mine':''}`;el.innerHTML=`<strong>${esc(m.sender?.name||(mine?'You':'HomeServe user'))}</strong><p>${esc(m.text)}</p><time>${new Date(m.createdAt).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'})}</time>`;list.appendChild(el);list.scrollTop=list.scrollHeight;}
async function load(){if(!bookingId){showError('Booking ID is missing.');form.hidden=true;return;}try{const r=await fetch(`${API}/${bookingId}`,{headers:{Authorization:`Bearer ${token}`},cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.message||'Unable to load chat');const b=d.booking;document.getElementById('bookingCode').textContent=b.bookingCode||'HomeServe booking';document.getElementById('chatTitle').textContent=b.service?.name||'Booking conversation';document.getElementById('chatMeta').textContent=`${b.customer?.name||'Customer'} ↔ ${b.provider?.name||'Assigned worker'}`;document.getElementById('chatStatus').textContent=b.status;document.getElementById('backLink').href=user.role==='provider'?'provider.html':'my-bookings.html';list.innerHTML='';d.messages.forEach(renderMessage);if(['Completed','Cancelled'].includes(b.status)){input.disabled=true;document.getElementById('sendBtn').disabled=true;input.placeholder='This conversation is closed.';}}catch(e){showError(e.message);form.hidden=true;}}
form.addEventListener('submit',async e=>{e.preventDefault();const text=input.value.trim();if(!text)return;const btn=document.getElementById('sendBtn');btn.disabled=true;try{const r=await fetch(`${API}/${bookingId}`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({text})});const d=await r.json();if(!r.ok)throw new Error(d.message||'Unable to send message');input.value='';renderMessage(d);showError('');}catch(e){showError(e.message)}finally{btn.disabled=false;input.focus();}});
try{const socket=io(window.location.origin);socket.on('chat-message',payload=>{if(String(payload.bookingId)===String(bookingId)&&String(payload.message.sender?._id||payload.message.sender)!==String(user.id||user._id))renderMessage(payload.message);});}catch(_){ }
load();
